server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: WARN
    com.example.gateway: DEBUG
    reactor.netty.http.server.AccessLog: INFO

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 5s
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: sugang-service
          uri: lb://sugang-service
          predicates:
            - Path=/sugang-service/**
      default-filters:
        - CircuitBreaker=myCircuitBreaker
        - name: Retry
          args:
            retries: 3
            series: # empty
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            exceptions:
              - java.net.ConnectException
#        - name: LoggingFilter
#          args:
#            preLogger: true
#            postLogger: true